apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugin-deployment
  labels:
    app: hugin
  namespace: tekst-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugin
  template:
    metadata:
      labels:
        app: hugin
    spec:
      containers:
      - name: hugin
        image: harbor.nb.no/tekst/hugin:<version>
        ports:
        - containerPort: 8000
        imagePullPolicy: Always