apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugin
  template:
    metadata:
      labels:
        app: hugin
    spec:
      containers:
        - name: app
          image: harbor.nb.no/tekst/hugin:<version>
          ports:
            - containerPort: 8000
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: hugin-service
spec:
  ports:
    - port: 8000
      name: http
      targetPort: 8000
  selector:
    app: hugin
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugin-ingress
spec:
  rules:
    - host: <host_url>
      http:
        paths:
          - path: /hugin
            pathType: Prefix
            backend:
              service:
                name: hugin-service
                port:
                  number: 8000
