on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  node_pull_request_check:
    name: Node pull request check
    uses: NationalLibraryOfNorway/tekst-workflows/.github/workflows/node-check.yml@feat/node-workflows
    with:
      ENVIRONMENT: "stage"
      NODE_VERSION: "20.17.0"
      BUILD_OUTPUT_PATH: ".next"
      SET_ENV: true
    secrets:
      VAULT_URL: ${{ secrets.VAULT_URL }}
      VAULT_SECRET_PATH: kv/team/text/data
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}